### PR TITLE
add Form API

### PR DESCRIPTION
**Pull request by Xuefeng-Zhu**

### CODE REVIEW

**Comment by hickford** [comment]
Nice work, let me take a look

**Comment by Xuefeng-Zhu** [comment]
Any comment?

**Comment by hickford** [comment]
Pardon me, looks great. I suppose one of us should write documentation.

**Comment by Xuefeng-Zhu** [comment]
I can do it.

**Comment by Xuefeng-Zhu** [comment]
Do you just want me to put the document in README?

**Pull request merged**
